# creates a private internal network called vm-net through which containers can communicate
networks:
  vm-net:
    driver: bridge

volumes:
  vmstorage-data: {}
  vmagent-data: {}
  vmselect-cache: {}
  grafana-data: {}

services:
  #exposting the write port only
  #other containers in the network can still reach the other ports
  vmstorage:
    build: ./vmstorage
    container_name: vmstorage
    restart: unless-stopped
    networks: [vm-net]
    ports:
      - "8482:8482"
    volumes:
      - vmstorage-data:/storage
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:8482/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  vminsert:
    build: ./vminsert
    container_name: vminsert
    restart: unless-stopped
    networks: [vm-net]
    ports:
     - "8480:8480"
    depends_on:
      vmstorage:
        condition: service_healthy

  vmselect:
    build: ./vmselect
    container_name: vmselect
    restart: unless-stopped
    networks: [vm-net]
    ports:
      - "8481:8481"
    volumes:
      - vmselect-cache:/cache
    depends_on:
      vmstorage:
        condition: service_healthy
  #no current way to interact with aggregations yaml
  #volume 2 denotes a bind mount for the aggregations yaml. We can trigger a hot reload via:
  #POST http://localhost:8429/-/reload
  vmagent:
    build: ./vmagent
    container_name: vmagent
    restart: unless-stopped
    networks: [vm-net]
    ports:
      - "8429:8429"
    volumes:
      - vmagent-data:/vmagentdata
      - ./vmagent/aggregations.yml:/etc/vmagent/aggregations.yml:ro
    depends_on:
      - vminsert
      #- vector
  grafana:
    build: ./grafana
    container_name: grafana
    restart: unless-stopped
    networks: [vm-net]
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - vmselect

  # vector:
  #   build: ./vector
  #   container_name: vector
  #   networks: [vm-net]
  #   ports:
  #     - "9090:9090"
  #   environment:
  #     - AWS_ACCESS_KEY_ID=placeholder
  #     - AWS_SECRET_ACCESS_KEY=placeholder
  #     - AWS_REGION=placeholder