import { pool } from "./database.js";
import { collectDashboardQueries, collectQueries } from "./grafanaApiInterface.js";
import { parsePromqlExpression } from "./promQLQueryParser.js";
import { getLabelValueCountsForMetric, getMetricsData } from "./vmSelectApiInterface.js";

export type RecommendationStatus = "pending" | "accepted" | "declined";
export type RecommendationStatusFilter = RecommendationStatus | "all";

type RecommendationRow = {
  id: string;
  metric_name: string;
  status: RecommendationStatus;
  problem_label: string;
  remaining_labels: string[];
  estimated_current_series: string;
  estimated_after_series: string;
  estimated_reduction_percent: string;
  explanation: string;
  decision_reason: string | null;
  yaml_content: string | null;
  created_at: Date;
  decided_at: Date | null;
};

type AggregationRow = {
  id: string;
  metric_name: string;
  labels: string[];
  json_snippet: Record<string, unknown>;
  aggregated: boolean;
  created_at: Date;
};

function formatRecommendation(row: RecommendationRow) {
  return {
    id: Number(row.id),
    metricName: row.metric_name,
    status: row.status,
    problemLabel: row.problem_label,
    remainingLabels: row.remaining_labels,
    estimatedCurrentSeries: Number(row.estimated_current_series),
    estimatedAfterSeries: Number(row.estimated_after_series),
    estimatedReductionPercent: Number(row.estimated_reduction_percent),
    explanation: row.explanation,
    decisionReason: row.decision_reason,
    yamlContent: row.yaml_content,
    createdAt: row.created_at.toISOString(),
    decidedAt: row.decided_at?.toISOString() ?? null,
  };
}

function labelsByMetricFromQueries(queries: string[]) {
  const labelsByMetric: Record<string, Set<string>> = {};

  for (const query of queries) {
    const { metrics, labels } = parsePromqlExpression(query);
    for (const metric of metrics) {
      labelsByMetric[metric] ??= new Set();
      labels.forEach((label) => labelsByMetric[metric]?.add(label));
    }
  }

  return Object.entries(labelsByMetric).map(([metricName, labels]) => ({
    metricName,
    labels: [...labels],
  }));
}

export async function getAiRecommendations(status: RecommendationStatusFilter = "pending") {
  if (status === "accepted" || status === "declined") {
    return {
      status,
      note:
        "The recommendations table is currently a pending cache. Accepted rules move into aggregations, and declined recommendations are not stored.",
      recommendations: [],
    };
  }

  if (status === "all") {
    const result = await pool.query<RecommendationRow>(
      `SELECT * FROM recommendations ORDER BY created_at DESC`
    );
    return {
      status,
      note:
        "This returns the current recommendation cache. Durable accepted rules live in aggregations.",
      recommendations: result.rows.map(formatRecommendation),
    };
  }

  const result = await pool.query<RecommendationRow>(
    `SELECT * FROM recommendations WHERE status = $1 ORDER BY created_at DESC`,
    [status]
  );

  return {
    status,
    note:
      "These are current pending recommendations. They are regenerated by the orchestrator and should be treated as a cache.",
    recommendations: result.rows.map(formatRecommendation),
  };
}

export async function getAiDecisionHistory(limit: number) {
  return {
    requestedLimit: Math.min(Math.max(limit, 1), 25),
    available: false,
    reason:
      "Metropolis does not currently persist declined recommendation history. Accepted recommendations are materialized as rows in the aggregations table.",
    acceptedRuleSource: "getAggregations",
  };
}

export async function getAiAggregations() {
  const result = await pool.query<AggregationRow>(
    `SELECT id, metric_name, labels, json_snippet, aggregated, created_at
     FROM aggregations
     ORDER BY created_at DESC`
  );

  return result.rows.map((row) => ({
    id: Number(row.id),
    metricName: row.metric_name,
    labels: row.labels,
    rule: row.json_snippet,
    aggregated: row.aggregated,
    createdAt: row.created_at.toISOString(),
  }));
}

export async function getAiGrafanaUsage(source: "all" | "queryHistory" | "dashboards") {
  const [queryHistoryEntries, dashboardQueries] = await Promise.all([
    source === "dashboards" ? Promise.resolve([]) : collectQueries(),
    source === "queryHistory" ? Promise.resolve([]) : collectDashboardQueries(),
  ]);

  const queryHistoryExpressions = (queryHistoryEntries ?? [])
    .flatMap((entry) => entry.queries.map((query) => query.expr))
    .filter((expr): expr is string => Boolean(expr));

  const dashboardExpressions = dashboardQueries ?? [];
  const expressions = [...queryHistoryExpressions, ...dashboardExpressions];

  return {
    source,
    generatedAt: new Date().toISOString(),
    queryHistory: {
      queryCount: queryHistoryExpressions.length,
      expressions: queryHistoryExpressions,
    },
    dashboards: {
      queryCount: dashboardExpressions.length,
      expressions: dashboardExpressions,
    },
    usedLabelsByMetric: labelsByMetricFromQueries(expressions),
  };
}

export async function getAiMetricSeriesBreakdown(date: string, metricName: string) {
  const parsedDate = new Date(date);

  if (metricName === "all") {
    const data = await getMetricsData(parsedDate);
    return {
      date,
      totalSeries: data.totalSeries,
      totalLabelValuePairs: data.totalLabelValuePairs,
      seriesCountByMetricName: data.seriesCountByMetricName,
      labelValueCountByLabelName: data.labelValueCountByLabelName,
    };
  }

  const data = await getLabelValueCountsForMetric(metricName, parsedDate);
  return {
    date,
    metricName,
    totalSeries: data.totalSeries,
    labelValueCountByLabelName: data.labelValueCountByLabelName,
    seriesCountByLabelName: data.seriesCountByLabelName,
    seriesCountByLabelValuePair: data.seriesCountByLabelValuePair,
  };
}

export async function getAiContext(date: string) {
  const pendingRecommendationResult = await getAiRecommendations("pending");
  const pendingRecommendations = pendingRecommendationResult.recommendations;
  const storedRules = await getAiAggregations();

  const statusCountResult = await pool.query<{ status: RecommendationStatus; count: string }>(
    `SELECT status, COUNT(*) FROM recommendations GROUP BY status`
  );

  const statusCounts = new Map(
    statusCountResult.rows.map((row) => [row.status, Number(row.count)])
  );

  const highestReductionRecommendation = pendingRecommendations.reduce<
    ReturnType<typeof formatRecommendation> | null
  >(
    (highest, current) => {
      if (!highest) return current;

      return current.estimatedReductionPercent >
        highest.estimatedReductionPercent
        ? current
        : highest;
    },
    null
  );

  return {
    date,
    generatedAt: new Date().toISOString(),
    summary: {
      pendingRecommendationCount: statusCounts.get("pending") ?? 0,
      storedRuleCount: storedRules.length,
      decisionHistoryAvailable: false,
      highestReductionRecommendation: highestReductionRecommendation
        ? {
            id: highestReductionRecommendation.id,
            metricName: highestReductionRecommendation.metricName,
            problemLabel: highestReductionRecommendation.problemLabel,
            estimatedReductionPercent:
              highestReductionRecommendation.estimatedReductionPercent,
          }
        : null,
    },
    storedRules,
    limitations: [
      "The recommendations table is a pending cache.",
      "Accepted recommendations are represented by rows in aggregations.",
      "Declined recommendation history is not currently persisted.",
    ],
  };
}
